<!-- 
RSS generated by JIRA (9.12.27#9120027-sha1:edc4490121e366e9e7bd2213d532dbe7e028fc5d) at Tue Sep 30 12:27:03 UTC 2025

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary append 'field=key&field=summary' to the URL of your request.
-->
<rss version="0.92" >
<channel>
    <title>Java Bug System</title>
    <link>https://bugs.openjdk.org</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-us</language>    <build-info>
        <version>9.12.27</version>
        <build-number>9120027</build-number>
        <build-date>02-09-2025</build-date>
    </build-info>


<item>
            <title>[JDK-8309067] gtest/AsyncLogGtest.java fails again in stderrOutput_vm</title>
                <link>https://bugs.openjdk.org/browse/JDK-8309067</link>
                <project id="10100" key="JDK">JDK</project>
                    <description>Failure mode appears the same as &lt;a href=&quot;https://bugs.openjdk.org/browse/JDK-8297302&quot; title=&quot;gtest/AsyncLogGtest.java fails AsyncLogTest.stdoutOutput_vm&quot; class=&quot;issue-link&quot; data-issue-key=&quot;JDK-8297302&quot;&gt;&lt;strike&gt;JDK-8297302&lt;/strike&gt;&lt;/a&gt; but in the stderr test. See on Linux aarch64.&lt;br/&gt;
&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:292: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:293: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:294: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stderrOutput_vm (0 ms)</description>
                <environment></environment>
        <key id="5102059">JDK-8309067</key>
            <summary>gtest/AsyncLogGtest.java fails again in stderrOutput_vm</summary>
                <type id="1" iconUrl="https://bugs.openjdk.org/secure/viewavatar?size=xsmall&amp;avatarId=14703&amp;avatarType=issuetype">Bug</type>
                                            <priority id="3" iconUrl="https://bugs.openjdk.org/images/jbsImages/p3.png">P3</priority>
                        <status id="5" iconUrl="https://bugs.openjdk.org/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status>
                    <statusCategory id="3" key="done" colorName="success"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="xliu">Xin Liu</assignee>
                                    <reporter username="dholmes">David Holmes</reporter>
                        <labels>
                            <label>amazon-interest</label>
                            <label>intermittent</label>
                            <label>jdk21u-fix-request</label>
                            <label>jdk21u-fix-yes</label>
                            <label>logging</label>
                            <label>noreg-self</label>
                            <label>tier6</label>
                    </labels>
                <created>Mon, 29 May 2023 15:30:36 -0700</created>
                <updated>Wed, 21 Aug 2024 01:59:44 -0700</updated>
                            <resolved>Tue, 21 Nov 2023 19:25:56 -0800</resolved>
                                    <version>17</version>
                    <version>21</version>
                                    <fixVersion>22</fixVersion>
                                    <component>hotspot</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>8</watches>
                                                                                                                <comments>
                            <comment id="14698629" author="JIRAUSER20917" created="Thu, 15 Aug 2024 19:55:26 -0700"  >&lt;br/&gt;
Fix request [21u]&lt;br/&gt;
&lt;br/&gt;
I backport this for parity with 21.0.5-oracle.&lt;br/&gt;
No risk, only a test change.&lt;br/&gt;
add added codes are clean, except line different.&lt;br/&gt;
SAP nightly testing passed.</comment>
                            <comment id="14698429" author="roboduke" created="Wed, 14 Aug 2024 23:24:57 -0700"  >A pull request was submitted for review.&lt;br/&gt;
Branch: master&lt;br/&gt;
URL: &lt;a href=&quot;https://git.openjdk.org/jdk21u-dev/pull/923&quot;&gt;https://git.openjdk.org/jdk21u-dev/pull/923&lt;/a&gt;&lt;br/&gt;
Date: 2024-08-15 06:18:52 +0000</comment>
                            <comment id="14628281" author="dukebot" created="Tue, 21 Nov 2023 19:25:56 -0800"  >Changeset: d1af748a&lt;br/&gt;
Author:    Xin Liu &amp;lt;&lt;a href=&apos;mailto:xliu@openjdk.org&apos;&gt;xliu@openjdk.org&lt;/a&gt;&amp;gt;&lt;br/&gt;
Date:      2023-11-22 03:23:45 +0000&lt;br/&gt;
URL:       &lt;a href=&quot;https://git.openjdk.org/jdk/commit/d1af748ab470e1068d03a8f8bc1a7445eff721fa&quot;&gt;https://git.openjdk.org/jdk/commit/d1af748ab470e1068d03a8f8bc1a7445eff721fa&lt;/a&gt;&lt;br/&gt;
</comment>
                            <comment id="14627525" author="roboduke" created="Mon, 20 Nov 2023 00:33:55 -0800"  >A pull request was submitted for review.&lt;br/&gt;
URL: &lt;a href=&quot;https://git.openjdk.org/jdk/pull/16728&quot;&gt;https://git.openjdk.org/jdk/pull/16728&lt;/a&gt;&lt;br/&gt;
Date: 2023-11-20 08:27:49 +0000</comment>
                            <comment id="14627450" author="xliu" created="Sun, 19 Nov 2023 16:31:59 -0800"  >I made a testcase to reproducible this.  as long as N is big enough &amp;gt;= 10000, it&amp;#39;s easy to trigger this error. &lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
make test TEST=&amp;quot;jtreg:gtest/AsyncLogGtest.java&amp;quot;  CONF=linux-x86_64-server-fastdebug&lt;br/&gt;
[ RUN      ] AsyncLogTest.bufferUpdater_vm&lt;br/&gt;
/home/xxinliu/Devel/jdk/test/hotspot/gtest/logging/test_asynclog.cpp:343: Failure&lt;br/&gt;
Value of: file_contains_substrings_in_order(TestLogFileName, lines)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.bufferUpdater_vm (334 ms)&lt;br/&gt;
[----------] 7 tests from AsyncLogTest (551 ms total)&lt;br/&gt;
&lt;br/&gt;
[----------] Global test environment tear-down&lt;br/&gt;
[==========] 7 tests from 1 test suite ran. (551 ms total)&lt;br/&gt;
[  PASSED  ] 6 tests.&lt;br/&gt;
[  FAILED  ] 1 test, listed below:&lt;br/&gt;
[  FAILED  ] AsyncLogTest.bufferUpdater_vm&lt;br/&gt;
&lt;br/&gt;
&amp;nbsp;1 FAILED TEST&lt;br/&gt;
ERROR: RUN_ALL_TESTS() failed. Error 1&lt;br/&gt;
&lt;br/&gt;
[2023-11-20T00:30:19.406692198Z] Waiting for completion for process 57644&lt;br/&gt;
[2023-11-20T00:30:19.406868200Z] Waiting for completion finished for process 57644&lt;br/&gt;
STDERR:&lt;br/&gt;
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::bufferUpdater_vm]&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at GTestWrapper.main(GTestWrapper.java:98)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:580)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at java.base/java.lang.Thread.run(Thread.java:1570)&lt;br/&gt;
&lt;br/&gt;
JavaTest Message: Test threw exception: java.lang.AssertionError&lt;br/&gt;
JavaTest Message: shutting down test&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
TEST RESULT: Failed. Execution failed: `main&amp;#39; threw exception: java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::bufferUpdater_vm]&lt;br/&gt;
--------------------------------------------------&lt;br/&gt;
Test results: failed: 1&lt;br/&gt;
Report written to /local/home/xxinliu/Devel/jdk/build/linux-x86_64-server-fastdebug/test-results/jtreg_test_hotspot_jtreg_gtest_AsyncLogGtest_java/html/report.html&lt;br/&gt;
Results written to /local/home/xxinliu/Devel/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_gtest_AsyncLogGtest_java&lt;br/&gt;
Error: Some tests failed or other problems occurred.&lt;br/&gt;
Finished running test &amp;#39;jtreg:test/hotspot/jtreg/gtest/AsyncLogGtest.java&amp;#39;&lt;br/&gt;
Test report is stored in build/linux-x86_64-server-fastdebug/test-results/jtreg_test_hotspot_jtreg_gtest_AsyncLogGtest_java&lt;br/&gt;
&lt;br/&gt;
==============================&lt;br/&gt;
Test summary&lt;br/&gt;
==============================&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;TEST                                              TOTAL  PASS  FAIL ERROR&lt;br/&gt;
&amp;gt;&amp;gt; jtreg:test/hotspot/jtreg/gtest/AsyncLogGtest.java     1     0     1     0 &amp;lt;&amp;lt;&lt;br/&gt;
==============================&lt;br/&gt;
TEST FAILURE&lt;br/&gt;
&lt;br/&gt;
make[1]: *** [main] Error 1&lt;br/&gt;
make: *** [test] Error 2&lt;br/&gt;
</comment>
                            <comment id="14627423" author="xliu" created="Sat, 18 Nov 2023 13:26:43 -0800"  >I believe I understand the rootcause of this. &lt;br/&gt;
AsyncLogWriter::write() has no lock-protection.  its job is to write out this-&amp;gt;_buffer_staging to disk. &lt;br/&gt;
&lt;br/&gt;
BufferUpdater::BufferUpdater(size_t newsize)  is abuser. it updates by force. &lt;br/&gt;
&amp;nbsp;&amp;nbsp;_instance-&amp;gt;_buffer_staging = new Buffer(newsize);&lt;br/&gt;
&lt;br/&gt;
the race condition is that AsyncLogWriter::write() has seen the change of BufferUpdater(). as a result, it emits nothing. &lt;br/&gt;
&lt;br/&gt;
next time when it wakes up from _lock.wait(0/* no timeout */), it then reset staging_buffer. as a result, we miss the contents in _buffer_staging. </comment>
                            <comment id="14627415" author="dcubed" created="Sat, 18 Nov 2023 07:49:57 -0800"  >Here&amp;#39;s a log file snippet from the jdk-22+25-1950-tier6 sighting:&lt;br/&gt;
&lt;br/&gt;
gtest/AsyncLogGtest.java&lt;br/&gt;
&lt;br/&gt;
----------System.out:(46/2244)----------&lt;br/&gt;
Command line: [/opt/mach5/mesos/work_dir/jib-master/install/jdk-22+25-1950/linux-x64-open.test/hotspot/gtest/server/gtestLauncher -jdk /opt/mach5/mesos/work_dir/jib-master/install/jdk-22+25-1950/linux-x64-open.jdk/jdk-22 --gtest_output=xml:test_result.xml --gtest_catch_exceptions=0 --gtest_filter=AsyncLogTest* -Xlog:async]&lt;br/&gt;
[2023-11-18T13:49:06.451899134Z] Gathering output for process 1555154&lt;br/&gt;
[2023-11-18T13:49:06.503732348Z] Waiting for completion for process 1555154&lt;br/&gt;
[2023-11-18T13:49:06.503983094Z] Waiting for completion finished for process 1555154&lt;br/&gt;
Output and diagnostic info for process 1555154 was saved into &amp;#39;pid-1555154-output.log&amp;#39;&lt;br/&gt;
Note: Google Test filter = AsyncLogTest*&lt;br/&gt;
[==========] Running 6 tests from 1 test suite.&lt;br/&gt;
[----------] Global test environment set-up.&lt;br/&gt;
[----------] 6 tests from AsyncLogTest&lt;br/&gt;
[ RUN      ] AsyncLogTest.asynclog_vm&lt;br/&gt;
[0.055s][warning][logging] 1Warning&lt;br/&gt;
[0.055s][error  ][logging] 1Error&lt;br/&gt;
[       OK ] AsyncLogTest.asynclog_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logBuffer_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logBuffer_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.droppingMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.droppingMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:275: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:276: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
[       OK ] AsyncLogTest.stderrOutput_vm (0 ms)&lt;br/&gt;
[----------] 6 tests from AsyncLogTest (57 ms total)&lt;br/&gt;
&lt;br/&gt;
[----------] Global test environment tear-down&lt;br/&gt;
[==========] 6 tests from 1 test suite ran. (57 ms total)&lt;br/&gt;
[  PASSED  ] 5 tests.&lt;br/&gt;
[  FAILED  ] 1 test, listed below:&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
&lt;br/&gt;
&amp;nbsp;1 FAILED TEST&lt;br/&gt;
ERROR: RUN_ALL_TESTS() failed. Error 1&lt;br/&gt;
&lt;br/&gt;
[2023-11-18T13:49:06.507995627Z] Waiting for completion for process 1555154&lt;br/&gt;
[2023-11-18T13:49:06.508129431Z] Waiting for completion finished for process 1555154&lt;br/&gt;
----------System.err:(10/615)----------&lt;br/&gt;
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]&lt;br/&gt;
	at GTestWrapper.main(GTestWrapper.java:98)&lt;br/&gt;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&lt;br/&gt;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&lt;br/&gt;
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)&lt;br/&gt;
	at java.base/java.lang.Thread.run(Thread.java:1570)&lt;br/&gt;
&lt;br/&gt;
JavaTest Message: Test threw exception: java.lang.AssertionError&lt;br/&gt;
JavaTest Message: shutting down test&lt;br/&gt;
&lt;br/&gt;
result: Failed. Execution failed: `main&amp;#39; threw exception: java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]</comment>
                            <comment id="14627413" author="dcubed" created="Sat, 18 Nov 2023 07:47:41 -0800"  >Here&amp;#39;s a log file snippet from the jdk-22+25-1943-tier6 sighting:&lt;br/&gt;
&lt;br/&gt;
gtest/AsyncLogGtest.java&lt;br/&gt;
&lt;br/&gt;
----------System.out:(51/2419)----------&lt;br/&gt;
Command line: [/opt/mach5/mesos/work_dir/jib-master/install/jdk-22+25-1943/linux-aarch64-open.test/hotspot/gtest/server/gtestLauncher -jdk /opt/mach5/mesos/work_dir/jib-master/install/jdk-22+25-1943/linux-aarch64-open.jdk/jdk-22 --gtest_output=xml:test_result.xml --gtest_catch_exceptions=0 --gtest_filter=AsyncLogTest* -Xlog:async]&lt;br/&gt;
[2023-11-18T03:56:40.326451176Z] Gathering output for process 2347225&lt;br/&gt;
[2023-11-18T03:56:40.388392104Z] Waiting for completion for process 2347225&lt;br/&gt;
[2023-11-18T03:56:40.388677746Z] Waiting for completion finished for process 2347225&lt;br/&gt;
Output and diagnostic info for process 2347225 was saved into &amp;#39;pid-2347225-output.log&amp;#39;&lt;br/&gt;
Note: Google Test filter = AsyncLogTest*&lt;br/&gt;
[==========] Running 6 tests from 1 test suite.&lt;br/&gt;
[----------] Global test environment set-up.&lt;br/&gt;
[----------] 6 tests from AsyncLogTest&lt;br/&gt;
[ RUN      ] AsyncLogTest.asynclog_vm&lt;br/&gt;
[0.065s][warning][logging] 1Warning&lt;br/&gt;
[0.065s][error  ][logging] 1Error&lt;br/&gt;
[       OK ] AsyncLogTest.asynclog_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logBuffer_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logBuffer_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.droppingMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.droppingMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:275: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:276: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:277: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
[       OK ] AsyncLogTest.stderrOutput_vm (0 ms)&lt;br/&gt;
[----------] 6 tests from AsyncLogTest (67 ms total)&lt;br/&gt;
&lt;br/&gt;
[----------] Global test environment tear-down&lt;br/&gt;
[==========] 6 tests from 1 test suite ran. (67 ms total)&lt;br/&gt;
[  PASSED  ] 5 tests.&lt;br/&gt;
[  FAILED  ] 1 test, listed below:&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
&lt;br/&gt;
&amp;nbsp;1 FAILED TEST&lt;br/&gt;
ERROR: RUN_ALL_TESTS() failed. Error 1&lt;br/&gt;
&lt;br/&gt;
[2023-11-18T03:56:40.393417783Z] Waiting for completion for process 2347225&lt;br/&gt;
[2023-11-18T03:56:40.393570105Z] Waiting for completion finished for process 2347225&lt;br/&gt;
----------System.err:(10/646)----------&lt;br/&gt;
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]&lt;br/&gt;
	at GTestWrapper.main(GTestWrapper.java:98)&lt;br/&gt;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&lt;br/&gt;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&lt;br/&gt;
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)&lt;br/&gt;
	at java.base/java.lang.Thread.run(Thread.java:1570)&lt;br/&gt;
&lt;br/&gt;
JavaTest Message: Test threw exception: java.lang.AssertionError&lt;br/&gt;
JavaTest Message: shutting down test&lt;br/&gt;
&lt;br/&gt;
result: Failed. Execution failed: `main&amp;#39; threw exception: java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]</comment>
                            <comment id="14627274" author="dcubed" created="Fri, 17 Nov 2023 09:22:47 -0800"  >Here&amp;#39;s a log file snippet from the jdk-22+24-1918-tier6 sighting:&lt;br/&gt;
&lt;br/&gt;
gtest/AsyncLogGtest.java&lt;br/&gt;
&lt;br/&gt;
----------System.out:(51/2419)----------&lt;br/&gt;
Command line: [/opt/mach5/mesos/work_dir/jib-master/install/jdk-22+24-1918/linux-aarch64-open.test/hotspot/gtest/server/gtestLauncher -jdk /opt/mach5/mesos/work_dir/jib-master/install/jdk-22+24-1918/linux-aarch64-open.jdk/jdk-22 --gtest_output=xml:test_result.xml --gtest_catch_exceptions=0 --gtest_filter=AsyncLogTest* -Xlog:async]&lt;br/&gt;
[2023-11-17T00:18:31.648325045Z] Gathering output for process 3811494&lt;br/&gt;
[2023-11-17T00:18:31.719540921Z] Waiting for completion for process 3811494&lt;br/&gt;
[2023-11-17T00:18:31.719908960Z] Waiting for completion finished for process 3811494&lt;br/&gt;
Output and diagnostic info for process 3811494 was saved into &amp;#39;pid-3811494-output.log&amp;#39;&lt;br/&gt;
Note: Google Test filter = AsyncLogTest*&lt;br/&gt;
[==========] Running 6 tests from 1 test suite.&lt;br/&gt;
[----------] Global test environment set-up.&lt;br/&gt;
[----------] 6 tests from AsyncLogTest&lt;br/&gt;
[ RUN      ] AsyncLogTest.asynclog_vm&lt;br/&gt;
[0.074s][warning][logging] 1Warning&lt;br/&gt;
[0.074s][error  ][logging] 1Error&lt;br/&gt;
[       OK ] AsyncLogTest.asynclog_vm (1 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logBuffer_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logBuffer_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.droppingMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.droppingMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:275: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:276: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:277: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
[       OK ] AsyncLogTest.stderrOutput_vm (0 ms)&lt;br/&gt;
[----------] 6 tests from AsyncLogTest (78 ms total)&lt;br/&gt;
&lt;br/&gt;
[----------] Global test environment tear-down&lt;br/&gt;
[==========] 6 tests from 1 test suite ran. (78 ms total)&lt;br/&gt;
[  PASSED  ] 5 tests.&lt;br/&gt;
[  FAILED  ] 1 test, listed below:&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
&lt;br/&gt;
&amp;nbsp;1 FAILED TEST&lt;br/&gt;
ERROR: RUN_ALL_TESTS() failed. Error 1&lt;br/&gt;
&lt;br/&gt;
[2023-11-17T00:18:31.726213029Z] Waiting for completion for process 3811494&lt;br/&gt;
[2023-11-17T00:18:31.726403109Z] Waiting for completion finished for process 3811494&lt;br/&gt;
----------System.err:(10/646)----------&lt;br/&gt;
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]&lt;br/&gt;
	at GTestWrapper.main(GTestWrapper.java:98)&lt;br/&gt;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&lt;br/&gt;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&lt;br/&gt;
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)&lt;br/&gt;
	at java.base/java.lang.Thread.run(Thread.java:1570)&lt;br/&gt;
&lt;br/&gt;
JavaTest Message: Test threw exception: java.lang.AssertionError&lt;br/&gt;
JavaTest Message: shutting down test&lt;br/&gt;
&lt;br/&gt;
result: Failed. Execution failed: `main&amp;#39; threw exception: java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm, AsyncLogTest::stdoutOutput_vm]</comment>
                            <comment id="14626968" author="xliu" created="Thu, 16 Nov 2023 09:50:07 -0800"  >thanks for the post. &lt;br/&gt;
I will keep looking into this issue. </comment>
                            <comment id="14626898" author="dcubed" created="Thu, 16 Nov 2023 06:34:26 -0800"  >Here&amp;#39;s a log file snippet from the jdk-22+24-1907-tier6 sighting:&lt;br/&gt;
&lt;br/&gt;
gtest/AsyncLogGtest.java&lt;br/&gt;
&lt;br/&gt;
#section:main&lt;br/&gt;
----------messages:(8/385)----------&lt;br/&gt;
command: main GTestWrapper --gtest_filter=AsyncLogTest* -Xlog:async&lt;br/&gt;
reason: User specified action: run main/native GTestWrapper --gtest_filter=AsyncLogTest* -Xlog:async &lt;br/&gt;
started: Thu Nov 16 03:21:32 UTC 2023&lt;br/&gt;
Mode: agentvm&lt;br/&gt;
Agent id: 11&lt;br/&gt;
Additional exports to unnamed modules from @modules: java.base/jdk.internal.misc&lt;br/&gt;
finished: Thu Nov 16 03:21:33 UTC 2023&lt;br/&gt;
elapsed time (seconds): 0.622&lt;br/&gt;
----------configuration:(15/1933)----------&lt;br/&gt;
&lt;br/&gt;
&amp;lt;snip&amp;gt;&lt;br/&gt;
&lt;br/&gt;
----------System.out:(51/2411)----------&lt;br/&gt;
Command line: [/opt/mach5/mesos/work_dir/jib-master/install/jdk-22+24-1907/linux-x64-open.test/hotspot/gtest/server/gtestLauncher -jdk /opt/mach5/mesos/work_dir/jib-master/install/jdk-22+24-1907/linux-x64-open.jdk/jdk-22 --gtest_output=xml:test_result.xml --gtest_catch_exceptions=0 --gtest_filter=AsyncLogTest* -Xlog:async]&lt;br/&gt;
[2023-11-16T03:21:33.398966070Z] Gathering output for process 3561155&lt;br/&gt;
[2023-11-16T03:21:33.465560556Z] Waiting for completion for process 3561155&lt;br/&gt;
[2023-11-16T03:21:33.465894161Z] Waiting for completion finished for process 3561155&lt;br/&gt;
Output and diagnostic info for process 3561155 was saved into &amp;#39;pid-3561155-output.log&amp;#39;&lt;br/&gt;
Note: Google Test filter = AsyncLogTest*&lt;br/&gt;
[==========] Running 6 tests from 1 test suite.&lt;br/&gt;
[----------] Global test environment set-up.&lt;br/&gt;
[----------] 6 tests from AsyncLogTest&lt;br/&gt;
[ RUN      ] AsyncLogTest.asynclog_vm&lt;br/&gt;
[0.070s][warning][logging] 1Warning&lt;br/&gt;
[0.070s][error  ][logging] 1Error&lt;br/&gt;
[       OK ] AsyncLogTest.asynclog_vm (1 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.logBuffer_vm&lt;br/&gt;
[       OK ] AsyncLogTest.logBuffer_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.droppingMessage_vm&lt;br/&gt;
[       OK ] AsyncLogTest.droppingMessage_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
[       OK ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:303: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:304: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:305: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stderrOutput_vm (1 ms)&lt;br/&gt;
[----------] 6 tests from AsyncLogTest (75 ms total)&lt;br/&gt;
&lt;br/&gt;
[----------] Global test environment tear-down&lt;br/&gt;
[==========] 6 tests from 1 test suite ran. (75 ms total)&lt;br/&gt;
[  PASSED  ] 5 tests.&lt;br/&gt;
[  FAILED  ] 1 test, listed below:&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
&lt;br/&gt;
&amp;nbsp;1 FAILED TEST&lt;br/&gt;
ERROR: RUN_ALL_TESTS() failed. Error 1&lt;br/&gt;
&lt;br/&gt;
[2023-11-16T03:21:33.472249975Z] Waiting for completion for process 3561155&lt;br/&gt;
[2023-11-16T03:21:33.472481236Z] Waiting for completion finished for process 3561155&lt;br/&gt;
----------System.err:(10/646)----------&lt;br/&gt;
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stderrOutput_vm, AsyncLogTest::stderrOutput_vm, AsyncLogTest::stderrOutput_vm]&lt;br/&gt;
	at GTestWrapper.main(GTestWrapper.java:98)&lt;br/&gt;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&lt;br/&gt;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&lt;br/&gt;
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)&lt;br/&gt;
	at java.base/java.lang.Thread.run(Thread.java:1570)&lt;br/&gt;
&lt;br/&gt;
JavaTest Message: Test threw exception: java.lang.AssertionError&lt;br/&gt;
JavaTest Message: shutting down test&lt;br/&gt;
&lt;br/&gt;
result: Failed. Execution failed: `main&amp;#39; threw exception: java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AsyncLogTest::stderrOutput_vm, AsyncLogTest::stderrOutput_vm, AsyncLogTest::stderrOutput_vm]</comment>
                            <comment id="14625902" author="dholmes" created="Mon, 13 Nov 2023 18:37:25 -0800"  >[~xliu] we have not seen a failure since the one reported on Nov 6th . So that was a few days before &lt;a href=&quot;https://bugs.openjdk.org/browse/JDK-8319554&quot; title=&quot;Select LogOutput* directly for stdout and stderr&quot; class=&quot;issue-link&quot; data-issue-key=&quot;JDK-8319554&quot;&gt;&lt;strike&gt;JDK-8319554&lt;/strike&gt;&lt;/a&gt; integrated, so we can&amp;#39;t conclude anything about that fix as yet.</comment>
                            <comment id="14625774" author="xliu" created="Mon, 13 Nov 2023 11:05:38 -0800"  >hi, @dholmes&lt;br/&gt;
Does error still occur after we merged &lt;a href=&quot;https://bugs.openjdk.org/browse/JDK-8319554&quot; title=&quot;Select LogOutput* directly for stdout and stderr&quot; class=&quot;issue-link&quot; data-issue-key=&quot;JDK-8319554&quot;&gt;&lt;strike&gt;JDK-8319554&lt;/strike&gt;&lt;/a&gt;?</comment>
                            <comment id="14624214" author="dholmes" created="Mon, 6 Nov 2023 17:18:58 -0800"  >&amp;gt; 1) are they all linux-aarch64? &lt;br/&gt;
&lt;br/&gt;
[~xliu] no it is Linux-x64 as well&lt;br/&gt;
&lt;br/&gt;
&amp;gt; 2) Do they always fail in line 292? the same tests apply to both stdout and stderr. if it only hit on stderr, that&amp;#39;s a big lead. &lt;br/&gt;
&lt;br/&gt;
No it is a mix of stdout and stderr, but mostly stdout&lt;br/&gt;
&lt;br/&gt;
Sample failures:&lt;br/&gt;
&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:292: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:293: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:294: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stderrOutput_vm (0 ms)&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:269: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:270: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
[ RUN      ] AsyncLogTest.stdoutOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:269: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:270: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stdoutOutput_vm (0 ms)&lt;br/&gt;
&lt;br/&gt;
[ RUN      ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:292: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:293: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:294: Failure&lt;br/&gt;
Value of: file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;Actual: false&lt;br/&gt;
Expected: true&lt;br/&gt;
&lt;br/&gt;
[  FAILED  ] AsyncLogTest.stderrOutput_vm (0 ms)</comment>
                            <comment id="14624167" author="xliu" created="Mon, 6 Nov 2023 11:54:44 -0800"  >another possibility is that the test failed to reconfigure &amp;#39;stderr&amp;#39; in the first place. &lt;br/&gt;
set_log_config(&amp;quot;stderr&amp;quot;, &amp;quot;logging=debug&amp;quot;) returns a boolean flag to indicate whether it succeeded. I found that we ignore it. &lt;br/&gt;
I create a new task for it. &lt;a href=&quot;https://bugs.openjdk.org/browse/JDK-8319554&quot; title=&quot;Select LogOutput* directly for stdout and stderr&quot; class=&quot;issue-link&quot; data-issue-key=&quot;JDK-8319554&quot;&gt;&lt;strike&gt;JDK-8319554&lt;/strike&gt;&lt;/a&gt;</comment>
                            <comment id="14624133" author="xliu" created="Mon, 6 Nov 2023 10:09:47 -0800"  >hi, @dholmes, &lt;br/&gt;
I start investigating this issue.  CI captured 16 times in past 6 months? &lt;br/&gt;
can we toke a closer look at them? &lt;br/&gt;
1) are they all linux-aarch64? &lt;br/&gt;
&lt;br/&gt;
2) Do they always fail in line 292?  the same tests apply to both stdout and stderr.  if it only hit on stderr, that&amp;#39;s a big lead. &lt;br/&gt;
[ RUN ] AsyncLogTest.stderrOutput_vm&lt;br/&gt;
open/test/hotspot/gtest/logging/test_asynclog.cpp:292: Failure &lt;br/&gt;
&lt;br/&gt;
If it also failed at different places, could you paste them? &lt;br/&gt;
&lt;br/&gt;
</comment>
                            <comment id="14623811" author="dholmes" created="Sun, 5 Nov 2023 16:35:13 -0800"  >Raising priority to P3. We continue to see this fail in our CI testing - now 16 times since original report.</comment>
                            <comment id="14585824" author="xliu" created="Tue, 30 May 2023 17:09:38 -0700"  >if unexpected results are seen at 292, it means 290 write_to_file  and 291 are both true. &lt;br/&gt;
&lt;br/&gt;
290   if (write_to_file(testing::internal::GetCapturedStderr())) {&lt;br/&gt;
291     EXPECT_TRUE(file_contains_substring(TestLogFileName, &amp;quot;header&amp;quot;));&lt;br/&gt;
292     EXPECT_TRUE(file_contains_substring(TestLogFileName, &amp;quot;LogStreamWithAsyncLogImpl&amp;quot;));&lt;br/&gt;
293     EXPECT_TRUE(file_contains_substring(TestLogFileName, &amp;quot;logStream msg1-msg2-msg3&amp;quot;));&lt;br/&gt;
294     EXPECT_TRUE(file_contains_substring(TestLogFileName, &amp;quot;logStream newline&amp;quot;));&lt;br/&gt;
&lt;br/&gt;
we capture stderr but only see &amp;quot;header&amp;quot;. missing 3 log lines via UL. &lt;br/&gt;
&lt;br/&gt;
Is that we only see this error on stderr or the datapoints we collected are so few that they only manifest on stderr? &lt;br/&gt;
&lt;br/&gt;
UL writes streams in universal way.  if we only encounter this problem on stdout/stder, I feel like this problem happens on gtest  &lt;br/&gt;
esting::internal::GetCapturedStderr(). &lt;br/&gt;
&lt;br/&gt;
LogFileStreamOutput&lt;br/&gt;
&amp;nbsp;&amp;nbsp;LogStdoutOutput&lt;br/&gt;
&amp;nbsp;&amp;nbsp;LogStderrOutput&lt;br/&gt;
&amp;nbsp;&lt;br/&gt;
&lt;br/&gt;
I don&amp;#39;t have a great way to pinpoint this problem. how about we just remove async logging test for stdout/stderr? </comment>
                            <comment id="14585746" author="xliu" created="Tue, 30 May 2023 13:28:27 -0700"  >looking into this issue. &lt;br/&gt;
&lt;br/&gt;
the patch of  &lt;a href=&quot;https://bugs.openjdk.org/browse/JDK-8297302&quot; title=&quot;gtest/AsyncLogGtest.java fails AsyncLogTest.stdoutOutput_vm&quot; class=&quot;issue-link&quot; data-issue-key=&quot;JDK-8297302&quot;&gt;&lt;strike&gt;JDK-8297302&lt;/strike&gt;&lt;/a&gt; applies to both stdout and stderr. &lt;br/&gt;
If it&amp;#39;s still happening, it suggests that we haven&amp;#39;t identified the root-cause.  </comment>
                            <comment id="14585687" author="mseledtsov" created="Tue, 30 May 2023 11:06:12 -0700"  >ILW = MLM = P4</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10200">
                    <name>Backport</name>
                                            <outwardlinks description="backported by">
                                        <issuelink>
            <issuekey id="5132522">JDK-8334851</issuekey>
        </issuelink>
            <issuelink>
            <issuekey id="5137185">JDK-8338721</issuekey>
        </issuelink>
                            </outwardlinks>
                                                        </issuelinktype>
                            <issuelinktype id="10003">
                    <name>Relates</name>
                                                                <inwardlinks description="relates to">
                                        <issuelink>
            <issuekey id="5087922">JDK-8297302</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="107280" name="testcase-8309067.patch" size="2027" author="xliu" created="Sun, 19 Nov 2023 16:33:10 -0800"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_10000" key="com.atlassian.jira.plugin.system.customfieldtypes:multiselect">
                        <customfieldname>CPU</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="19300"><![CDATA[aarch64]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_11700" key="com.atlassian.jira.plugins.jira-development-integration-plugin:devsummary">
                        <customfieldname>Development</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                                                        <customfield id="customfield_10600" key="com.oracle.jira.javabugsystem-jira-plugin:jbs-fixedBackportedCustomfield">
                        <customfieldname>Fixed</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                            <customfield id="customfield_10005" key="com.atlassian.jira.plugin.system.customfieldtypes:multiselect">
                        <customfieldname>OS</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="17023"><![CDATA[linux]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                            <customfield id="customfield_11100" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>0|i31pnn:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_11004" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>9223372036854775807</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10006" key="com.atlassian.jira.plugin.system.customfieldtypes:select">
                        <customfieldname>Resolved In Build</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="17357"><![CDATA[b26]]></customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10008" key="com.oracle.jira.jira-subcomponent-plugin:oracle-subComponentField">
                        <customfieldname>Subcomponent</customfieldname>
                        <customfieldvalues>
                             <customfieldvalue key="192"><![CDATA[runtime]]></customfieldvalue> 
                        </customfieldvalues>
                    </customfield>
                                                                                                                        <customfield id="customfield_10601" key="com.oracle.jira.javabugsystem-jira-plugin:jbs-targetBackportedCustomfield">
                        <customfieldname>Targeted</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                    </customfields>
    </item>
</channel>
</rss>